
configfile: 'config.yaml'

INPUT_DIR=config['input_dir']
INPUT_GRAPHS=config['input_graphs']
OUTPUT_DIR = config['output_dir']

SIZE_THRESHOLDS = config['size_thresholds']

rule all_measure:
    input:
        expand(OUTPUT_DIR+"measures/{genome}_s{size}.txt",genome=INPUT_GRAPHS,size=SIZE_THRESHOLDS)

rule calc_measure:
    input:
        genome=INPUT_DIR+"{genome}.gfa.gz",
        binary="../../target/release/carp"
    output:
        OUTPUT_DIR+"measures/{genome}_s{size}.txt"
    threads:
        16
    log:
         std=OUTPUT_DIR+"logs/carp_{genome}_s{size}.log",
         err=OUTPUT_DIR+"logs/carp_{genome}_s{size}.errlog"
    benchmark:
        OUTPUT_DIR+"bench/carp_{genome}_s{size}.txt"
    shell:
        '{input.binary} --gfa {input.genome} -t {threads} -m {output} -s {wildcards.size} > {log.std} 2> {log.err}'

        
rule compile:
    output:
        "../../target/release/carp"
    shell:
        "cd ..; cargo build --release"
