[package]
name = "scj-carp-rust"
version = "0.1.0"
edition = "2025"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.29", features = ["derive"] }
csv = "1.3.1"
flate2 = "1.1.2"
itertools = "0.14.0"


