zombi_home : '/prj/gsp/urm/spp_dcj_v2/tools/ZOMBI_01042020/'
n_samples : 1 #for testing purposes. Original: 100
transfer_rates : [0.125,0.25,0.5,1,2,4,8,16,32]
tree_scales : [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1]